### ISSUE TITLE
Build using Boost 1.55 fails

### ISSUE THREAD

**Issue by oTTer-Chief** [FairRootGroup/DDS#143]
Building tag 1.2 fails on Debian 8.5 with boost 1.55 installed.
Linker error:

    Linking CXX executable dds-submit-localhost
    CMakeFiles/dds-submit-localhost.dir/src/main.cpp.o: In function `main::{lambda(dds::intercom_api::SSubmit const&)#1}::operator()(dds::intercom_api::SSubmit const&) const [clone .isra.292]':
    main.cpp:(.text+0x642): undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
    collect2: error: ld returned 1 exit status
    plugins/dds-submit-localhost/CMakeFiles/dds-submit-localhost.dir/build.make:103: recipe for target 'plugins/dds-submit-localhost/dds-submit-localhost' failed
    make[2]: *** [plugins/dds-submit-localhost/dds-submit-localhost] Error 1
    CMakeFiles/Makefile2:2146: recipe for target 'plugins/dds-submit-localhost/CMakeFiles/dds-submit-localhost.dir/all' failed
    make[1]: *** [plugins/dds-submit-localhost/CMakeFiles/dds-submit-localhost.dir/all] Error 2
    Makefile:137: recipe for target 'all' failed
    make: *** [all] Error 2 

Building against boost 1.59 (from fairsoft) on the same machine works fine.

**Comment by AnarManafov** [comment]
Either you are facing a known bug in boost 1.55 or your boost hasn't been built with C++11 support. C++11 is a must for DDS.

**Comment by oTTer-Chief** [comment]
The Boost 1.55 version comes with the distribution and is installed from official Debian repository. No chance to change this.
Is there a workaround available or is it just not usable with Debian for the moment?

**Comment by AnarManafov** [comment]
No need to change that broken one. Just build up your own version (I'd recommend the latest one, 1.61). BOOST is very easy to build.
